language: go
go_import_path: github.com/namsral/multipass

go:
  - 1.7.1

os:
  - linux

script:
  - go test -v ./...
  - go vet $(go list ./...)
  - go build github.com/namsral/multipass/cmd/multipass
